In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d rizwan123456789/potato-disease-leaf-datasetpld

 88% 33.0M/37.4M [00:00<00:00, 80.0MB/s]
100% 37.4M/37.4M [00:00<00:00, 76.8MB/s]


In [ ]:
import zipfile
zip_ref = zipfile.ZipFile('/content/potato-disease-leaf-datasetpld.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
import tensorflow as tf
print("GPU is", "available" if tf.config.list_physical_devices('GPU') else "NOT AVAILABLE")

GPU is available


In [ ]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PLD_3_Classes_256/Training',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 3251 files belonging to 3 classes.


In [ ]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PLD_3_Classes_256/Validation',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 416 files belonging to 3 classes.


In [ ]:
cnn = tf.keras.models.Sequential()

In [ ]:

# Convolutional layers
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128, 128, 3]))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Dropout layer
cnn.add(tf.keras.layers.Dropout(0.25))

# Flatten layer
cnn.add(tf.keras.layers.Flatten())

# Fully connected layers
cnn.add(tf.keras.layers.Dense(units=1500, activation='relu'))
#cnn.add(tf.keras.layers.Dropout(0.4))

# Output layer
cnn.add(tf.keras.layers.Dense(units=3, activation='softmax'))  # Changed units to 3 for 3 classes

# Compile the model
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])





In [ ]:
training_history = cnn.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
102/102 [==============================] - 7s 71ms/step - loss: 0.7634 - accuracy: 0.6696 - val_loss: 1.0805 - val_accuracy: 0.7188
Epoch 2/10
102/102 [==============================] - 7s 68ms/step - loss: 0.7168 - accuracy: 0.7112 - val_loss: 0.8225 - val_accuracy: 0.7692
Epoch 3/10
102/102 [==============================] - 8s 73ms/step - loss: 0.5225 - accuracy: 0.7954 - val_loss: 0.4190 - val_accuracy: 0.8726
Epoch 4/10
102/102 [==============================] - 7s 70ms/step - loss: 0.4081 - accuracy: 0.8394 - val_loss: 0.3991 - val_accuracy: 0.8389
Epoch 5/10
102/102 [==============================] - 7s 68ms/step - loss: 0.4047 - accuracy: 0.8404 - val_loss: 0.3102 - val_accuracy: 0.8870
Epoch 6/10
102/102 [==============================] - 7s 67ms/step - loss: 0.3103 - accuracy: 0.8757 - val_loss: 0.2729 - val_accuracy: 0.8918
Epoch 7/10
102/102 [==============================] - 7s 69ms/step - loss: 0.2859 - accuracy: 0.8896 - val_loss: 0.2684 - val_accuracy: 0.8894

In [ ]:

'''
import matplotlib.pyplot as plt

# Extract the accuracy and loss values from the training history
accuracy = training_history.history['accuracy']
loss = training_history.history['loss']
val_accuracy = training_history.history['val_accuracy']
val_loss = training_history.history['val_loss']

# Create a figure and axes
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

# Plot the accuracy and validation accuracy
ax[0].plot(accuracy, label='Training Accuracy')
ax[0].plot(val_accuracy, label='Validation Accuracy')
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('Accuracy')
ax[0].legend()

# Plot the loss and validation loss
ax[1].plot(loss, label='Training Loss')
ax[1].plot(val_loss, label='Validation Loss')
ax[1].set_xlabel('Epoch')
ax[1].set_ylabel('Loss')
ax[1].legend()

# Display the plots
plt.tight_layout()
plt.show()'''


"\nimport matplotlib.pyplot as plt\n\n# Extract the accuracy and loss values from the training history\naccuracy = training_history.history['accuracy']\nloss = training_history.history['loss']\nval_accuracy = training_history.history['val_accuracy']\nval_loss = training_history.history['val_loss']\n\n# Create a figure and axes\nfig, ax = plt.subplots(1, 2, figsize=(10, 5))\n\n# Plot the accuracy and validation accuracy\nax[0].plot(accuracy, label='Training Accuracy')\nax[0].plot(val_accuracy, label='Validation Accuracy')\nax[0].set_xlabel('Epoch')\nax[0].set_ylabel('Accuracy')\nax[0].legend()\n\n# Plot the loss and validation loss\nax[1].plot(loss, label='Training Loss')\nax[1].plot(val_loss, label='Validation Loss')\nax[1].set_xlabel('Epoch')\nax[1].set_ylabel('Loss')\nax[1].legend()\n\n# Display the plots\nplt.tight_layout()\nplt.show()"

In [ ]:
#Validation set Accuracy
val_loss, val_acc = cnn.evaluate(validation_set)
rounded_accuracy = round(val_acc * 100,)
print('Validation accuracy =', rounded_accuracy,'%')

13/13 [==============================] - 0s 20ms/step - loss: 0.2486 - accuracy: 0.9135
Validation accuracy = 91 %


In [ ]:
# Save the entire model to a file
cnn.save("crop_disease_detection_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
cnn.save('trained_plant_disease_model.keras')

In [ ]:
class_name = validation_set.class_names

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PLD_3_Classes_256/Validation',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 416 files belonging to 3 classes.


In [ ]:
y_pred = cnn.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

416/416 [==============================] - 2s 2ms/step


In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

<tf.Tensor: shape=(416,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
     

In [ ]:
predicted_categories

<tf.Tensor: shape=(416,), dtype=int64, numpy=
array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 1, 2, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
     

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
# Precision Recall Fscore
print(classification_report(Y_true,predicted_categories,target_names=class_name))

              precision    recall  f1-score   support

Early_Blight       0.97      0.87      0.91       163
     Healthy       0.83      0.99      0.91       102
 Late_Blight       0.97      0.95      0.96       151

    accuracy                           0.93       416
   macro avg       0.92      0.94      0.93       416
weighted avg       0.93      0.93      0.93       416



In [ ]:
#cnn = tf.keras.models.load_model('trained_plant_disease_model.keras')


In [ ]:
'''import cv2
image_path = '/content/WhatsApp Image 2024-04-08 at 21.04.09_36bd2444.jpg'
# Reading an image in default mode
img = cv2.imread(image_path)
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB) #Converting BGR to RGB
# Displaying the image
plt.imshow(img)
plt.title('Test Image')
plt.xticks([])
plt.yticks([])
plt.show()'''

"import cv2\nimage_path = '/content/WhatsApp Image 2024-04-08 at 21.04.09_36bd2444.jpg'\n# Reading an image in default mode\nimg = cv2.imread(image_path)\nimg = cv2.cvtColor(img,cv2.COLOR_BGR2RGB) #Converting BGR to RGB\n# Displaying the image\nplt.imshow(img)\nplt.title('Test Image')\nplt.xticks([])\nplt.yticks([])\nplt.show()"

In [ ]:
'''import numpy as np
image = tf.keras.preprocessing.image.load_img(image_path,target_size=(128,128))
input_arr = tf.keras.preprocessing.image.img_to_array(image)
input_arr = np.array([input_arr])  # Convert single image to a batch.
predictions = cnn.predict(input_arr)'''

'import numpy as np\nimage = tf.keras.preprocessing.image.load_img(image_path,target_size=(128,128))\ninput_arr = tf.keras.preprocessing.image.img_to_array(image)\ninput_arr = np.array([input_arr])  # Convert single image to a batch.\npredictions = cnn.predict(input_arr)'

In [ ]:
#print(predictions)

In [ ]:
#result_index = np.argmax(predictions) #Return index of max element
#print(result_index)

In [ ]:
# Displaying the disease prediction
'''model_prediction = class_name[result_index]
plt.imshow(img)
plt.title(f"Disease Name: {model_prediction}")
plt.xticks([])
plt.yticks([])
plt.show()'''

'model_prediction = class_name[result_index]\nplt.imshow(img)\nplt.title(f"Disease Name: {model_prediction}")\nplt.xticks([])\nplt.yticks([])\nplt.show()'